### ISSUE TITLE
module not installing properly

### ISSUE THREAD

**Issue by irbrad** [waldoapp/wdio-service#13]
I'm following the steps on https://www.npmjs.com/package/@waldoapp/wdio-service#installation and the module isn't installing properly.  I get the following error when I try to run wdio: `Error: Error: Failed to initialise launcher service unknown: Error: Couldn't find plugin "@waldoapp/wdio-service" service, neither as wdio scoped package "@wdio/@waldoapp/wdio-service-service" nor as community package "wdio-@waldoapp/wdio-service-service". Please make sure you have it installed!`

Looking at the @waldoapp/wdio-service directory in node_modules looks fairly empty.  I'm using node v20.17.0 but I also tried v18.20.4

<img width="712" alt="image" src="https://github.com/user-attachments/assets/729d9a78-f032-46a0-82a4-d850bcfe3c13">

**Comment by vbfox** [comment]
Hi, sorry for the late answer but I don't know what happened here.

The versions present on npm all contains the `dist` directory with the source code: https://www.runpkg.com/?@waldoapp/wdio-service@1.0.0/dist/index.js
